# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/health
    username: root
    password: green502
    jdbc-url: jdbc:mariadb://localhost:3306/health

# mybatis config
mybatis:
  type-aliases-package: com.example.health.model
  mapper-locations: mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/health/

server:
  port: 8081


---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/health
  sql:
    init:
      mode: always
      schema-locations: classpath:init/schema.sql
      data-locations: classpath:init/data.sql